import SearchInput from "./searchInput";

export const metadata = {
    title: 'Item List',
    description: 'Generated by create next app',
}

interface LayoutProps {
    children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({
    children,
}) => {
    return ( 
        <>
            <SearchInput/>
            {children}
        </>
     );
}
 
export default Layout;
